const defaultHighlights = [
  "Live mentor-led sessions",
  "1500+ students enrolled",
  "No Cost EMI available",
  "Course Duration: 3–6 Months",
  "Certificate on completion",
];

const defaultWhyFeatures = [
  {
    title: "Industry-Ready Skills",
    desc: "Learn practical skills that employers and clients actually pay for — not just theory.",
    icon: "graduation",
  },
  {
    title: "Placement & Freelance Support",
    desc: "Resume reviews, portfolio building, and guidance to land your first paid project.",
    icon: "briefcase",
  },
  {
    title: "Community & Mentors",
    desc: "Join a network of ambitious students and get doubt support from real practitioners.",
    icon: "shield",
  },
  {
    title: "100% Flexible Learning",
    desc: "Live + recorded classes. Study from anywhere with schedules built for students.",
    icon: "tablet",
  },
];

const defaultEligibility = [
  {
    eligible: true,
    title: "College Students (Any Stream)",
    desc: "If you're in school or college and want skills beyond textbooks, you're welcome.",
  },
  {
    eligible: true,
    title: "Working Professionals",
    desc: "Flexible schedule — no need to quit your job. Learn on evenings and weekends.",
  },
  {
    eligible: true,
    title: "Aspiring Freelancers & Creators",
    desc: "Perfect if you want to earn online alongside studies or a full-time role.",
  },
  {
    eligible: true,
    title: "Entrepreneurs & Side Hustlers",
    desc: "Build marketing, tech, and business skills while growing your own venture.",
  },
  {
    eligible: false,
    title: "Not Ready to Practice",
    desc: "This program needs weekly practice. Passive watching alone won't get results.",
  },
];

const defaultClasses = [
  {
    id: 1,
    title: "Introduction & Roadmap",
    duration: "45 min",
    status: "completed",
    scheduledAt: "2026-05-10T18:00",
    meetingLink: "",
    platform: "zoom",
    notes: "",
  },
  {
    id: 2,
    title: "Core Concepts — Module 1",
    duration: "1 hr 20 min",
    status: "live",
    scheduledAt: "2026-05-19T19:00",
    meetingLink: "https://zoom.us/j/example-live",
    platform: "zoom",
    notes: "Notebook ready rakho. 5 min pehle join karna.",
  },
  {
    id: 3,
    title: "Hands-on Workshop",
    duration: "1 hr",
    status: "upcoming",
    scheduledAt: "2026-05-22T19:00",
    meetingLink: "https://meet.google.com/example-upcoming",
    platform: "meet",
    notes: "Laptop mandatory hai is session ke liye.",
  },
  {
    id: 4,
    title: "Real Project Build",
    duration: "2 hr",
    status: "upcoming",
    scheduledAt: "2026-05-26T19:00",
    meetingLink: "",
    platform: "zoom",
    notes: "",
  },
  {
    id: 5,
    title: "Career & Monetization Q&A",
    duration: "1 hr",
    status: "upcoming",
    scheduledAt: "2026-05-30T19:00",
    meetingLink: "",
    platform: "meet",
    notes: "",
  },
];

const batches = [
  {
    courseId: 1,
    headerTitle: "AI Mastery",
    title: "AI MASTERY BATCH",
    teacherName: "Rahul Sharma",
    category: "Quick Skills",
    language: "HINDI",
    type: "Live Batch",
    startsOn: "Starts on 20th May'26",
    price: "Free",
    priceLabel: "Free",
    headerBg: "bg-teal-600",
    status: "live",
  },
  {
    courseId: 2,
    headerTitle: "Freelancing Blueprint",
    title: "FREELANCING BLUEPRINT",
    teacherName: "Priya Mehta",
    category: "Bootcamp",
    language: "ENGLISH",
    type: "Bootcamp",
    startsOn: "Starts on 25th May'26",
    price: "₹1,999",
    priceLabel: "₹1,999",
    headerBg: "bg-teal-700",
    status: "live",
  },
  {
    courseId: 3,
    headerTitle: "Content Creator",
    title: "CONTENT CREATOR ACCELERATOR",
    teacherName: "Arjun Patel",
    category: "Full Track",
    language: "HINDI",
    type: "Career Track",
    startsOn: "Starts on 1st Jun'26",
    price: "₹2,499",
    priceLabel: "₹2,499",
    headerBg: "bg-cyan-700",
    status: "upcoming",
  },
  {
    courseId: 4,
    headerTitle: "Startup From Zero",
    title: "STARTUP FROM ZERO",
    teacherName: "Vikram Malhotra",
    category: "Bootcamp",
    language: "ENGLISH",
    type: "Bootcamp",
    startsOn: "Starts on 10th Jun'26",
    price: "₹2,999",
    priceLabel: "₹2,999",
    headerBg: "bg-teal-600",
    status: "upcoming",
  },
  {
    courseId: 5,
    headerTitle: "Digital Marketing Pro",
    title: "DIGITAL MARKETING PRO",
    teacherName: "Sneha Reddy",
    category: "Quick Skills",
    language: "HINDI",
    type: "Live Batch",
    startsOn: "Starts on 18th May'26",
    price: "Free",
    priceLabel: "Free",
    headerBg: "bg-teal-700",
    status: "live",
  },
  {
    courseId: 6,
    headerTitle: "Data Careers",
    title: "DATA CAREERS KICKSTART",
    teacherName: "Amit Verma",
    category: "Full Track",
    language: "ENGLISH",
    type: "Career Track",
    startsOn: "Starts on 15th Jun'26",
    price: "₹3,499",
    priceLabel: "₹3,499",
    headerBg: "bg-cyan-800",
    status: "upcoming",
  },
  {
    courseId: 7,
    headerTitle: "YouTube Growth",
    title: "YOUTUBE GROWTH MASTERCLASS",
    teacherName: "Arjun Patel",
    category: "Quick Skills",
    language: "HINDI",
    type: "Live Batch",
    startsOn: "Starts on 22nd May'26",
    price: "₹999",
    priceLabel: "₹999",
    headerBg: "bg-teal-600",
    status: "live",
  },
  {
    courseId: 8,
    headerTitle: "ChatGPT for Students",
    title: "CHATGPT FOR STUDENTS",
    teacherName: "Rahul Sharma",
    category: "Quick Skills",
    language: "ENGLISH",
    type: "Self Paced",
    startsOn: "Starts on 28th May'26",
    price: "Free",
    priceLabel: "Free",
    headerBg: "bg-teal-700",
    status: "live",
  },
  {
    courseId: 9,
    headerTitle: "Design & Canva Pro",
    title: "DESIGN & CANVA PRO",
    teacherName: "Kavya Nair",
    category: "Bootcamp",
    language: "HINDI",
    type: "Bootcamp",
    startsOn: "Starts on 5th Jun'26",
    price: "₹1,499",
    priceLabel: "₹1,499",
    headerBg: "bg-cyan-700",
    status: "upcoming",
  },
];

export function buildCourseDocuments() {
  return batches.map((batch) => ({
    ...batch,
    bannerBg: "bg-violet-600",
    highlights: defaultHighlights,
    whyLabel: "WHY THIS COURSE?",
    whyTitle: "Career Outcomes You Can Actually Count On",
    whyFeatures: defaultWhyFeatures,
    eligibility: defaultEligibility,
    classes: defaultClasses,
    specializationTitle: `What You'll Master in ${batch.headerTitle}`,
    specializationItems: [
      "Foundations & mindset",
      "Tools & workflows",
      "Real-world projects",
      "Monetization & career paths",
    ],
  }));
}
